Platform.JHMobile/Controllers/信息门户Controller.cs
using Platform.JHMobile.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace Platform.JHMobile.Controllers
{
    public class 信息门户Controller : OfficeController
    {
        private int per = 10;

        public ActionResult 首页()
        {
            if (string.IsNullOrEmpty(Account))
                return 认证();
            var mo = DB.f______信息门户模块表().ToList().Select(o => new 信息门户对象模块 { 模块 = o, 数量 = 0/*DB.f______计数信息门户数(Account, o.ModuleTypeID.ToString()).Single().Value*/ }).ToList();
            return View(mo);
        }

        public ActionResult 信息门户列表()
        {
            if (string.IsNullOrEmpty(Account))
                return 认证();
            var sp = RouteData.Values["id"].ToString().Split(new char[] { '_' });
            var type = sp[0];
            var count = DB.f______计数信息门户数(Account, type).Single();
            ViewBag.Max = count % per == 0 ? count / per - 1 : (count + (per - count % per)) / per - 1;
            ViewBag.Module = type;
            ViewBag.Title = sp[1];
            return View();
        }

        public ActionResult 信息门户列表单页()
        {
            if (string.IsNullOrEmpty(Account))
                return 认证();
            var sp = RouteData.Values["id"].ToString().Split(new char[] { '_' });
            var type = sp[0];
            var id = int.Parse(sp[1]);
            ViewBag.Current = id + 1;
            var list = DB.f______列表信息门户表(Account, type).OrderByDescending(o => o.SendTime).Skip(id * per).Take(per).ToList();
            return View(list);
        }

        public ActionResult 信息门户列表内容()
        {
            if (string.IsNullOrEmpty(Account))
                return 认证();
            var id = RouteData.Values["id"]?.ToString();
            var int_id = int.Parse(id);
            var message = DB.f______信息门户内容表(int_id).FirstOrDefault();
            ViewBag.ModuleTypeID = message.ModuleTypeID;
            ViewBag.ModuleTypeName = DB.f______信息门户模块表().Single(o => o.ModuleTypeID == message.ModuleTypeID.Value).ModuleTypeName;
            DB.f______信息门户转已阅(int_id, message.ModuleTypeID.ToString(), Account);
            if (!string.IsNullOrEmpty(message.MessageFileName))
            {
                var name = message.MessageFileName.Split(new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries).Last();
                var dir = new DirectoryInfo(Directory + "\\Resource\\MessageFile");
                ViewBag.Path = "";
                var people = DB.f______信息门户已阅表(message.MessageID, message.ModuleTypeID.ToString()).OrderBy(o => o).ToList();
                ViewBag.PeopleCount = people.Count;
                ViewBag.PeopleRead = people.Aggregate("", (o, s) => o += s + "、", o => (o.Length == 0 ? "无" : o.Substring(0, o.Length - 1)));
                foreach (var cDir in dir.GetDirectories().OrderByDescending(o => o.CreationTime))
                {
                    if (cDir.GetFiles().Count(o => o.Name.ToLower() == name.ToLower()) > 0)
                    {
                        string path = dir + "\\" + cDir.Name + "\\" + name;
                        ViewBag.Link = path;
                        var converted = ConvertDoc(path);
                        if (!string.IsNullOrEmpty(converted))
                        {
                            ViewBag.PDF = converted;
                        }
                    }
                }
            }
            var query = DB.f______信息门户附件表(message.MessageID.ToString()).OrderBy(o => o.FileID);
            var list = query == null ? new List<f______信息门户附件表_Result>() : query.ToList();
            foreach (var path in list)
            {
                var source = Directory + path.FilePath.Substring(3).Replace("/", "\\");
                var destination = source.Replace("__", "h__");
                DecryptFile(source, destination);
            }
            var mo = new 信息门户对象内容();
            mo.内容 = message;
            mo.附件 = list;
            return View(mo);
        }
    }
}

Platform.JHMobile/Controllers/首页Controller.cs
using Platform.JHMobile.Models;
using System.Linq;
using System.Web.Mvc;

namespace Platform.JHMobile.Controllers
{
    public class 首页Controller : OfficeController
    {
        public ActionResult 首页()
        {
            if (string.IsNullOrEmpty(Account))
                return 认证();
            /*ViewBag.已收寻呼数 = DB.f______计数寻呼未阅数(Account).Single()*//* + DB.f______计数寻呼已阅数(Account).Single() + DB.f______计数寻呼历史数(Account).Single()*//*;*/
            //var mo = DB.f______信息门户模块表().ToList().Select(o => new 信息门户对象模块 { 模块 = o, 数量 = DB.f______计数信息门户数(Account, o.ModuleTypeID.ToString()).Single().Value }).ToList();
            //ViewBag.信息门户数 = mo.Sum(o => o.数量);
            //ViewBag.待阅信息数 = DB.f______计数待阅信息数(Account).Single();
            //ViewBag.待办工作数 = DB.f______计数待办工作数(Account).Single();
            //ViewBag.流程查询数 = DB.f______计数流程查询数(Account).Single();
            return View();
        }
    }
}

Platform.JHMobile/Views/信息门户/信息门户列表.cshtml
<script>
    var _index = 0;
    var _max = @ViewBag.Max;
    var _module= @ViewBag.Module;

    $(document).ready(function () {
        if(_max >=0)
            loadList();
        else
            $("#handler").hide();
    });

    function loadList() {
        $("#handler").hide();
        var href = '@Url.Action("信息门户列表单页", "信息门户")' + "/" + _module + "_" + _index;
        $.ajax({
            url: href,
            type: "GET",
            success: function (data) {
                $("#area").append(data);
                _index++;
                if(_index > _max)
                    $("#handler").hide();
                else
                    $("#handler").show();
            },
            error: function () {
            }
        });
    }
</script>
<div id="area" class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1 class="page-heading" style="margin: 5px;">@ViewBag.Title</h1>
            <div class="the-box toolbar no-border no-margin">
                <div class="row">
                    <div class="col-xs-7">
                        <div class="btn btn-warning" type="button" onclick="top.location = '@Url.Action("首页", "首页")';">
                            <i class="fa fa-home fa-lg"></i>
                        </div>
                        <div class="btn btn-warning" type="button" onclick="top.location = '@Url.Action("首页", "信息门户")';">
                            <i class="fa fa-reply fa-lg"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">&nbsp;</div>
</div>
<div id="handler" class="container">
    <div class="row">
        <div class="col-xs-12 text-center">
            <input class="btn btn-warning" type="button" value="显示更多" onclick="loadList();" />
        </div>
    </div>
</div>

Platform.JHMobile/Views/信息门户/信息门户列表内容.cshtml
@using Platform.JHMobile.Models
@model 信息门户对象内容
<div id="area" class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1 class="page-heading" style="margin-top: 5px; margin-bottom: 5px;">门户信息查看</h1>
            <div class="the-box toolbar no-border no-margin">
                <div class="row">
                    <div class="col-xs-7">
                        <div class="btn btn-warning" type="button" onclick="top.location = '@Url.Action("首页", "首页")';">
                            <i class="fa fa-home fa-lg"></i>
                        </div>
                        <div class="btn btn-warning" type="button" onclick="top.location = '@Url.Action("信息门户列表", "信息门户", new { id = ViewBag.ModuleTypeID + "_" + ViewBag.ModuleTypeName })';">
                            <i class="fa fa-reply fa-lg"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">&nbsp;</div>
    <div class="row">
        <div class="col-md-12"><h4><strong>@Model.内容.MessageTitle</strong></h4></div>
        <div class="col-xs-5">发布人：@Model.内容.UserName</div>
        <div class="col-xs-7 text-right">发布时间：@Model.内容.SendTime.Value.ToString("yyyy-MM-dd")</div>
        <div class="col-md-12">&nbsp;</div>
        <div class="col-md-12 text-center">已阅@(ViewBag.PeopleCount)人</div>
        <div class="col-md-12">&nbsp;</div>
        <div class="col-md-12">
            @Html.Raw(Model.内容.MessageHTML)
            @{
                if (!string.IsNullOrEmpty(ViewBag.PDF))
                {
                    <input id="pdfPath" type="hidden" value="@string.Format("../../{0}", ViewBag.PDF.Replace(OfficeController.Directory, "").Replace("\\", "/"))" />
                    <iframe id="viewer" style="width: 100%; height: 389px;" src="~/PDFViewer/web/viewer.html"></iframe>
                }
            }
        </div>
        @{
            if (!string.IsNullOrEmpty(ViewBag.PDF))
            {
                <div class="col-md-12 text-center">
                    <a class="btn btn-warning" target="_blank" href="@string.Format("../../{0}", ViewBag.Link.Replace(OfficeController.Directory, "").Replace("\\", "/"))">正文下载</a>
                </div>
            }
        }
        <div class="col-md-12">&nbsp;</div>
        @{
            if (Model.附件.Count > 0)
            {
                <div class="col-md-12">附件：</div>
                foreach (var file in Model.附件)
                {
                    <div class="col-md-12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a target="_blank" href="@(Url.Content("~/") + file.FilePath.Substring(3).Replace("__", "h__"))">@file.FileName</a></div>
                }
                <div class="col-md-12">&nbsp;</div>
            }
        }
        <div class="col-md-12">已阅人员：</div>
        <div class="col-md-12">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@ViewBag.PeopleRead</div>
        <div class="row">&nbsp;</div>
    </div>
</div>

Platform.JHMobile/Views/信息门户/信息门户列表单页.cshtml
@using Platform.JHMobile.Models
@model List<信息门户对象简略>
@{
    foreach (var obj in Model)
    {
        <div class="row" onclick="top.location = '@Url.Action("信息门户列表内容", "信息门户", new { id = obj.MessageID })';">
            <div class="col-xs-12">
                <div class="chat-wrap scroll-chat-widget">
                    <ul class="media-list media-xs media-dotted media-chat">
                        <li class="media">
                            <a class="pull-left" href="#">
                                <img class="media-object img-circle" src="~/Content/img/信息门户.jpg" alt="" />
                            </a>
                            <div class="media-body" style="background-color:#fff;">
                                <p class="name" style="background-color:#5C96F7; padding:8px">
                                    <small><span>@Html.Raw(obj.MessageTitle)</span></small>
                                </p>
                                <p class="small">
                                    <div class="row">
                                        <div class="col-xs-8 text-left">
                                            <div>@obj.SendTime.Value.ToString("yyyy-MM-dd HH:mm:ss")</div>
                                        </div>
                                        <div class="col-xs-4 text-right">
                                            <div>@obj.UserName</div>
                                        </div>
                                    </div>
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }
}
<div class="row">
    <div class="col-md-12 text-center">
        -&nbsp;&nbsp;&nbsp;&nbsp;第&nbsp;@(ViewBag.Current)&nbsp;页&nbsp;&nbsp;&nbsp;&nbsp;-
    </div>
</div>
<div class="row">&nbsp;</div>

Platform.JHMobile/Views/信息门户/首页.cshtml
@using Platform.JHMobile.Models
@model List<信息门户对象模块>
@{
    ViewBag.Title = "信息门户";
}
<div class="container">
    <div class="row">
        <div class="col-xs-12 metro_left metro_right">
            <h1 class="page-heading" style="margin: 5px;">信息门户</h1>
            <div class="the-box toolbar no-border no-margin">
                <div class="row">
                    <div class="col-xs-7">
                        <div class="btn btn-warning" type="button" onclick="top.location = '@Url.Action("首页", "首页")';">
                            <i class="fa fa-home fa-lg"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">&nbsp;</div>
    @{
        for (var i = 0; i < Model.Count; i++)
        {
            if (i % 2 == 0)
            {
                <div class="row">
                    <div class="col-xs-6 metro_left">
                        <div class="metro metro_2" onclick="top.location = '@Url.Action("信息门户列表", "信息门户", new { id = Model[i].模块.ModuleTypeID + "_" + Model[i].模块.ModuleTypeName })';">
                            <div><i class="fa fa-envelope fa-5x"></i></div>
                            <div class="metro_text">@Model[i].模块.ModuleTypeName</div>
                        </div>
                    </div>
                    @{
                        if ((i + 1) < Model.Count)
                        {
                            <div class="col-xs-6 metro_right">
                                <div class="metro metro_2" onclick="top.location = '@(Url.Action("信息门户列表", "信息门户") + "/" + Model[i + 1].模块.ModuleTypeID + "_" + Model[i + 1].模块.ModuleTypeName)';">
                                    <div><i class="fa fa-envelope fa-5x"></i></div>
                                    <div class="metro_text">@Model[i + 1].模块.ModuleTypeName</div>
                                </div>
                            </div>
                        }
                    }
                </div>
            }
        }
    }
</div>