Platform.Contact/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Homory.Model;

namespace Platform.Contact.Controllers
{
    public class DepartmentController : Controller
    {
        private Entities db = new Entities();

        private static readonly Guid TopDepartmentId = Guid.Parse("A885E587-8CF5-4CDA-B212-08D359727E88");

        public ActionResult Index()
        {
            var departmentId = RouteData.Values.ContainsKey("id") ? Guid.Parse(RouteData.Values["id"].ToString()) : TopDepartmentId;
            var departments = db.Contact_GetDepartments(departmentId).OrderBy(d => d.Ordinal).ToList();
            var users = db.Contact_GetDepartmentUsers(departmentId).OrderBy(u => u.Ordinal).ToList();
            return View(new DepartmentObject { Departments = departments, Users = users });
        }
    }

    public class DepartmentObject
    {
        public List<Department> Departments { get; set; }
        public List<Contact_Users> Users { get; set; }
    }
}

Platform.Contact/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Platform.Contact.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Platform.Contact/Controllers/QueryController.cs
using Homory.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Platform.Contact.Controllers
{
    public class QueryController : Controller
    {
        private Entities db = new Entities();

        public ActionResult Index()
        {
            var search = RouteData.Values["id"] == null ? "" : Server.UrlDecode(RouteData.Values["id"].ToString()).Trim().ToLower();
            if (search.Length > 0)
            {
                var users = db.Contact_GetUsers(search).OrderBy(u => u.RealName).ToList();
                return View(users);
            }
            else
            {
                return View(new List<Contact_Users>());
            }
        }
    }
}

Platform.Contact/Controllers/UserController.cs
using Homory.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Platform.Contact.Controllers
{
    public class UserController : Controller
    {
        private Entities db = new Entities();

        public ActionResult Index()
        {
            var search = RouteData.Values["id"] == null ? "" : Server.UrlDecode(RouteData.Values["id"].ToString()).ToLower();
            var users = db.Contact_GetDepartmentVIPUsers().OrderBy(u => u.RealName).ToList();
            if (!string.IsNullOrEmpty(search))
            {
                users = users.Where(o => o.CampusName.ToLower().Contains(search) || o.RealName.ToLower().Contains(search) || o.PinYin.ToLower().Contains(search) || o.Phone.Contains(search)).ToList();
            }
            users.RemoveAll(u => users.Count(x => x.Id == u.Id) > 1 && u.Type == -2);
            return View(users);
        }
    }
}

Platform.Contact/Views/Department/Index.cshtml
@model Platform.Contact.Controllers.DepartmentObject

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>局部门</title>
</head>
<body>
    <ul>
        @{
            foreach (var department in Model.Departments)
            {
                <li>
                    @Html.ActionLink(@department.Name, "Index", new { id = department.Id })
                </li>
            }
        }
    </ul>
    <ul>
        @{
            foreach (var user in Model.Users)
            {
                <li>
                    <ul>
                        <li>
                            单位：@user.CampusName
                        </li>
                        <li>
                            姓名：@user.RealName
                        </li>
                        <li>
                            手机号码：@user.Phone
                        </li>
                        <li>
                            头像：<img src="@user.Icon" style="width: 120px; height: 120px;" />
                        </li>
                        <li>
                            主职：@(user.PerStaff ? "是" : "否")
                        </li>
                    </ul>
                </li>
            }
        }
    </ul>
</body>
</html>

Platform.Contact/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>首页</title>
</head>
<body>
    <ul>
        <li>@Html.ActionLink("局部门", "Index", "Department")</li>
        <li>@Html.ActionLink("局人员", "Index", "User")</li>
        <li>@Html.ActionLink("大数据", "Index", "Query")</li>
    </ul>
</body>
</html>

Platform.Contact/Views/Query/Index.cshtml
@model List<Homory.Model.Contact_Users>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>大数据</title>
    <script>
        function searching() {
            top.location.href = "http://oa.wxlxjy.com:888/Contact/Query/Index/" + encodeURIComponent(document.getElementById("search").value.trim());
        }
    </script>
</head>
<body>
    <div>
        <input id="search" type="text" />
        <input type="submit" value="检索" onclick="searching();" />
    </div>
    <ul>
        @{
            foreach (var user in Model)
            {
                <li>
                    <ul>
                        <li>
                            单位：@user.CampusName
                        </li>
                        <li>
                            姓名：@user.RealName
                        </li>
                        <li>
                            手机号码：@user.Phone
                        </li>
                        <li>
                            头像：<img src="@user.Icon" style="width: 120px; height: 120px;" />
                        </li>
                        <li>
                            主职：@(user.PerStaff ? "是" : "否")
                        </li>
                    </ul>
                </li>
            }
        }
    </ul>
</body>
</html>

Platform.Contact/Views/User/Index.cshtml
@model List<Homory.Model.Contact_Users>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>局人员</title>
    <script>
        function searching() {
            top.location.href = "http://localhost:57785/User/Index/" + encodeURIComponent(document.getElementById("search").value.trim());
        }
    </script>
</head>
<body>
    <div>
        <input id="search" type="text" />
        <input type="submit" value="检索" onclick="searching();" />
    </div>
    <ul>
        @{
            foreach (var user in Model)
            {
                <li>
                    <ul>
                        <li>
                            单位：@user.CampusName
                        </li>
                        <li>
                            姓名：@user.RealName
                        </li>
                        <li>
                            手机号码：@user.Phone
                        </li>
                        <li>
                            头像：<img src="@user.Icon" style="width: 120px; height: 120px;" />
                        </li>
                        <li>
                            主职：@(user.PerStaff ? "是" : "否")
                        </li>
                    </ul>
                </li>
            }
        }
    </ul>
</body>
</html>